<?php
$this->headTitle('Login');

$this->mainMenu()->setActiveItemId('login');

$form->get('email')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Email address',
    'autofocus' => true
]);

$form->get('password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Password',
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);
$form->get('submit')->setValue('Login');
$form->prepare();

?>

<div class="d-flex justify-content-center">
    <div class="p-4">
        <h2>Log in to your account</h2>
        <?= $this->form()->openTag($form); ?>
        <?php if ($isLoginError) : ?>
            <div class="alert alert-warning" role="alert">
                Incorrect login and/or password.
            </div>
        <?php endif; ?>
        <div class="form-group">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('password')); ?>
            <?= $this->formElement($form->get('password')); ?>
            <?= $this->formElementErrors($form->get('password')); ?>
        </div>
        <?= $this->formElement($form->get('redirect_url')); ?>
        <?= $this->formElement($form->get('csrf')) ?>
        <?= $this->formElement($form->get('submit')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>