<?php
$this->headTitle('Edit ' . $post->getTitle());
$this->mainMenu()->setActiveItemId('admin');

$form = $this->form;
$form->get('title')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Enter post title here'
]);
$form->get('description')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Type description here',
    'rows' => 6
]);
$form->get('draft')->setAttributes([
    'class' => 'form-check-input'
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);
$form->get('submit')->setValue('Edit');
$form->prepare();

?>

<div class="p-3">
    <h2>Edit post "<?= $post->getTitle() ?>"</h2>
    <br>
    <?= $this->form()->openTag($form); ?>

    <div class="form-group">
        <?= $this->formLabel($form->get('title')); ?>
        <?= $this->formElement($form->get('title')); ?>
        <?= $this->formElementErrors($form->get('title')); ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($form->get('description')); ?>
        <?= $this->formElement($form->get('description')); ?>
        <?= $this->formElementErrors($form->get('description')); ?>
    </div>
    <div class="form-check">
        <?= $this->formElement($form->get('draft')); ?>
        <?= $this->formLabel($form->get('draft')); ?>
        <?= $this->formElementErrors($form->get('draft')); ?>
    </div>

    <?= $this->formElement($form->get('submit')); ?>
    <a class="btn btn-default" href="<?= $this->url('posts', ['action' => 'admin']); ?>">
        Cancel
    </a>

    <?= $this->form()->closeTag(); ?>
</div>