<?php
$this->headTitle($post->getTitle());
$this->mainMenu()->setActiveItemId('admin');

$form = $this->form;
$form->get('user')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Your name'
]);
$form->get('comment')->setAttributes([
    'class' => 'form-control',
    'rows' => 6,
    'placeholder' => 'Text'
]);
$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);
$form->prepare();
?>

<div class="text-center">
    <h1><?php
        echo $this->escapeHtml($post->getTitle());
        echo ($post->getDraft()) ? ' (DRAFT)' : '';
        ?></h1>
    <hr style="width: 50%;">

    <p class="text-secondary">
        <?= $this->escapeHtml(date('F j, Y', strtotime($post->getDateCreated()))); ?> |
        <?= $this->escapeHtml($postManager->getCommentCountStr($post)); ?>
    </p>
</div>

<p class="p-4"><?= nl2br($post->getDescription()); ?></p>
<hr>
<h4><?= $this->escapeHtml($postManager->getCommentCountStr($post)); ?></h4>

<?php foreach ($post->getComments() as $comment) : ?>
    <hr>
    <p>
        <h5><?= $this->escapeHtml($comment->getUser()) ?></h5>
        <p class="text-secondary"><?= $this->escapeHtml(date('F j, Y', strtotime($comment->getDateCreated()))); ?> at
            <?= $this->escapeHtml(date('h:i A', strtotime($comment->getDateCreated()))); ?></p>
    </p>

    <p>
        <?= nl2br($comment->getContent()); ?>
    </p>
<?php endforeach; ?>

<hr>

<a name="comment"></a>
<h4>Leave a reply</h4>

<div class="row">
    <div class="col-md-8">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('user')); ?>
            <?= $this->formElement($form->get('user')); ?>
            <?= $this->formElementErrors($form->get('user')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('comment')); ?>
            <?= $this->formElement($form->get('comment')); ?>
            <?= $this->formElementErrors($form->get('comment')); ?>
        </div>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>