<?php
$this->headTitle('Admin Area - User');
$this->mainMenu()->setActiveItemId('admin');

$form = $this->form;
$form->get('email')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Enter email here',
]);

$form->get('old_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Enter old password',
]);

$form->get('new_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Enter new password'
]);

$form->get('confirm_new_password')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Re-enter new password'
]);

$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);
$form->get('submit')->setValue('Edit');
$form->prepare();

$helper = $this->formElementErrors();
$helper->setMessageOpenFormat('<div class="alert alert-danger">');
$helper->setMessageSeparatorString('</div><div class="alert alert-danger">');
$helper->setMessageCloseString('</div>');

?>

<div class="p-3">
    <h2>Admin Management Area - User</h2>
    <?= $flashMessage ?>
    <?= $this->form()->openTag($form); ?>
    <p>Pass: testing</p>
    <div class="form-group">
        <?= $this->formLabel($form->get('email')); ?>
        <?= $this->formElement($form->get('email')); ?>
        <?= $this->formElementErrors($form->get('email')); ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($form->get('old_password')); ?>
        <?= $this->formElement($form->get('old_password')); ?>
        <?= $this->formElementErrors($form->get('old_password')); ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($form->get('new_password')); ?>
        <?= $this->formElement($form->get('new_password')); ?>
        <?= $this->formElementErrors($form->get('new_password')); ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($form->get('confirm_new_password')); ?>
        <?= $this->formElement($form->get('confirm_new_password')); ?>
        <?= $this->formElementErrors($form->get('confirm_new_password')); ?>
    </div>

    <?= $this->formElement($form->get('submit')); ?>
    <?= $this->form()->closeTag(); ?>
</div>