<?php
$this->headTitle('Homepage');
?>

<div class="header">
    <img src="/img/header.jpg" class="img-fluid rounded" />
    <div class="mt-3 mb-5">
        <h1 class="text-center display-1 p-3">Bloggie</h1>
        <p class="text-center font-italic text-secondary">"The mind is it's own palace, and in itself it can make a heaven of hell, a hell of heaven."</p>
    </div>
</div>

<div class="row justify-content-between">
    <div class="col-md-8">

        <?php foreach ($posts as $post) : ?>
            <hr>
            <br>
            <h2 class="display-5">
                <a href="<?= $this->url('posts', ['action' => 'view', 'id' => $post->getId()]); ?>" style="text-decoration: none" class="text-dark">
                    <?= $this->escapeHtml($post->getTitle()); ?>
                </a>
            </h2>
            <hr>
            <p class="text-secondary">
                <?= $this->escapeHtml(date('F j, Y', strtotime($post->getDateCreated()))); ?> |
                <?= $this->escapeHtml($postManager->getCommentCountStr($post)); ?>
            </p>

            <p> <?php
                if (strlen($post->getDescription()) > 500) {
                    echo substr(nl2br($post->getDescription()), 0, 500) . '...';
                    echo '<br>';
                    echo '<a href="' . $this->url('posts', ['action' => 'view', 'id' => $post->getId()]) . '" style="text-decoration: none" >';
                    echo 'Continue reading';
                    echo '</a>';
                } else {
                    echo nl2br($post->getDescription());
                }
                ?> </p>
        <?php endforeach; ?>

        <?= $this->paginationControl(
            $posts,
            'Sliding',
            'application/partial/paginator',
            array('route' => 'application')
        ); ?>

    </div>
    <div class="col-md-3 mt-3">
        <div class="border bg-light rounded p-3">
            <i>My name is Huong, and this is my small blog.
                <br><br>Thank you for visiting.
                <br><br>For any further contact, please send me an email: vuthuhuonghanoi@gmail.com
            </i>
        </div>
    </div>
</div>